const tools = [
    { name: "AdwCleaner", version: "V4.104", description: "decsription", link: null },
    { name: "Altium", version: "V20", description: "decsription", link: null },
    { name: "Arduino IDE", version: "V2.3.3", description: "decsription", link: null },
    { name: "Autocom", version: "V2021.11", description: "decsription", link: null },
    { name: "BalenaEtcher", version: "V1.18.11", description: "decsription", link: null },
    { name: "Beyond Compare", version: "V4.4.3", description: "decsription", link: null },
    { name: "CMake", version: "V3.28.5", description: "decsription", link: null },
    { name: "DeamonTools", version: "V12.1", description: "decsription", link: null },
    { name: "DiskInternals Linux Reader", version: "V4.2", description: "decs", link: null },
    { name: "ECANTools", version: "V1.1", description: "decsription", link: null },
    { name: "Ender3Pro", version: "V3", description: "decsription", link: null },
    { name: "Executable File Explorer", version: "V3.5.1", description: "decs", link: null },
    { name: "Frhed", version: "V1.7.1", description: "decsription", link: null },
    { name: "Git", version: "V2.45", description: "decsription", link: null },
    { name: "HackRF", version: "V2024.02.1", description: "decsription", link: null },
    { name: "Hantek HT6004BX", version: "V1", description: "decsription", link: null },
    { name: "HDSDR", version: "V1", description: "decsription", link: null },
    { name: "Java", version: "V22", description: "decsription", link: null },
    { name: "LibreOffice", version: "V24.2.3", description: "decsription", link: null },
    { name: "LTSpice", version: "V17.1.6", description: "decsription", link: null },
    { name: "Maple", version: "V2022", description: "decsription", link: null },
    { name: "Matlab", version: "V1", description: "decsription", link: null },
    { name: "MicroCap", version: "V12", description: "decsription", link: null },
    { name: "MinGW", version: "V12", description: "decsription", link: null },
    { name: "Mp3tag", version: "V3.14", description: "decsription", link: null },
    { name: "NGSpice", version: "V42", description: "decsription", link: null },
    { name: "NodeJS", version: "V20.11.1", description: "decsription", link: null },
    { name: "Octave", version: "V9.1.0", description: "decsription", link: null },
    { name: "PaintNet", version: "V5.0.13", description: "decsription", link: null },
    { name: "ProcessExplorer", version: "V1", description: "decsription", link: null },
    { name: "ProcessMonitor", version: "V1", description: "decsription", link: null },
    { name: "Putty", version: "V0.81", description: "decsription", link: null },
    { name: "Python", version: "V3.12.3", description: "decsription", link: null },
    { name: "Rkill", version: "V1", description: "decsription", link: null },
    { name: "Rufus", version: "V3.4", description: "decsription", link: null },
    { name: "Saleae", version: "V2.4.14", description: "decsription", link: null },
    { name: "SDRSharp", version: "V1", description: "decsription", link: null },
    { name: "Simple Web Server", version: "V1.2.8", description: "decsription", link: null },
    { name: "SpecAnalyzer", version: "V1", description: "decsription", link: null },
    { name: "SprintLayout", version: "V6", description: "decsription", link: null },
    { name: "SQLite Database Browser", version: "V1", description: "decsription", link: null },
    { name: "STM32 ST-LINK Utility", version: "V4.6", description: "decsription", link: null },
    { name: "STM32CubeIDE", version: "V1.9.0", description: "decsription", link: null },
    { name: "TCC", version: "V0.9.27", description: "decsription", link: null },
    { name: "Total Commander", version: "V9.22", description: "decsription", link: null },
    { name: "Universal-USB-Installer", version: "V1.9.6.2", description: "decsription", link: null },
    { name: "VMA Simple Spectrum Analyser", version: "V2019", description: "decsription", link: null },
    { name: "VMWare", version: "V17", description: "decsription", link: null },
    { name: "VSCode", version: "V1.89", description: "decsription", link: null },
    { name: "Wireshark", version: "V4.2.4", description: "decsription", link: null },
    { name: "XElfViewer", version: "V0.05", description: "decsription", link: null },
];



/*
linux tools??
*/